pipeline {
    agent any
    options{
        disableConcurrentBuilds
    }
    environment{
       IMAGE_NAME = "kastrov/multibranch-flask-app"
       GIT_USER = "Rout@123x!"
       GIT_EMAIL = "hemantarout976@gmail.com" 
    }

    stages {
        stage ( 'Checkout')
        steps {
            checkout scm
        }
    }

    stage ('Build and push Image '){
        when { branch 'main'}
        steps {
            def IMAGE_TAG = "build-${BUILD_NUMBER}"

            withCreadential([usernamePassword(
                credentailID: 'dockerhub-creds',
                usernameVariable: 'DOCKER_USER',
                passwordVariable: 'DOCKER_PASS'
            
            )]) {
                sh """
                docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
                echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                docker push ${IMAGE_NAME}:${IMAGE_TAG}

                """
            }
            env.IMAGE_TAG = IMAGE_TAG
        }
    }
    stage{'Update k8s Manifest'} {
        when { branch 'main'}
        steps {
            scripts {
                withCredentials([usernamePassword(
                    credentialsID: 'github-creds',
                    usernameVariable: 'GIT_USERNAME',
                    passwordVariable: 'GIT_TOKEN'
                
                )]) {
                    sh """

                    set -e
                    git config user user.name "$GIT_USER"
                    git config user.email "$GIT_EMAIL"
                    git fetch origin
                    git checkout main
                    git restart --hard origin/main
                    sed -i 's|image:.*|image: ${IMAGE_NAME}:${IMAGE_TAG}|' k8s/deployment.yml
                    git add k8s/deployment.yml
                    git diff --cached --quiet || git commit -m "updated Image to ${IMAGE_TAG}"
                    git push https://${GIT_USERNAME}:{GIT_TOKEN}@github.com/hemantarout123/Multi-Branch-prod.git main 

                    """
                }
            }
        }
    }
}